/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mwathsilu
 */
public class VehicleRegistration extends javax.swing.JFrame {

    /**
     * Creates new form VehicleRegistration
     */
    public VehicleRegistration() {
        initComponents();
        displayVehicleData();

        tblcar.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int selectedRow = tblcar.getSelectedRow();
                if (selectedRow != -1) {
                    // A row is selected, enable the Delete button
                    deletebtn.setEnabled(true);
                } else {
                    // No row is selected, disable the Delete button
                    deletebtn.setEnabled(false);
                }
            }
        });

    }

    private void clearFormFields() {
        jidtxt.setText("");
        jmodeltxt.setText("");
        jyeartxt.setText("");
        jmiletxt.setText("");
        jcosttxt.setText("");
        jdeposittxt.setText("");
        combo1.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jdeposittxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jmodeltxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jyeartxt = new javax.swing.JTextField();
        combo1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcosttxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        addbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        update1 = new javax.swing.JButton();
        jidtxt = new javax.swing.JTextField();
        jmiletxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        dashlbl = new javax.swing.JLabel();
        vlbl = new javax.swing.JLabel();
        clbl = new javax.swing.JLabel();
        inlbl = new javax.swing.JLabel();
        outlbl = new javax.swing.JLabel();
        loglbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcar = new javax.swing.JTable();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(227, 244, 255));

        jPanel4.setBackground(new java.awt.Color(227, 244, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(749, 170));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Prepayment");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Vehicle ID");

        jdeposittxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jdeposittxt.setForeground(new java.awt.Color(0, 102, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Vehicle model");

        jmodeltxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmodeltxt.setForeground(new java.awt.Color(0, 102, 153));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Year");

        jyeartxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jyeartxt.setForeground(new java.awt.Color(0, 102, 153));
        jyeartxt.setMinimumSize(new java.awt.Dimension(64, 20));

        combo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        combo1.setForeground(new java.awt.Color(0, 102, 153));
        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select--", "YES", "NO" }));
        combo1.setPreferredSize(new java.awt.Dimension(64, 22));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Mileage");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Cost per day");

        jcosttxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcosttxt.setForeground(new java.awt.Color(0, 102, 153));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Availability");

        addbtn.setBackground(new java.awt.Color(51, 0, 102));
        addbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addbtn.setForeground(new java.awt.Color(255, 255, 255));
        addbtn.setText("SAVE");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        deletebtn.setBackground(new java.awt.Color(51, 0, 102));
        deletebtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(255, 255, 255));
        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        update1.setBackground(new java.awt.Color(51, 0, 102));
        update1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        update1.setForeground(new java.awt.Color(255, 255, 255));
        update1.setText("UPDATE");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });

        jidtxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jidtxt.setForeground(new java.awt.Color(0, 102, 153));

        jmiletxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmiletxt.setForeground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jcosttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(24, 24, 24)
                            .addComponent(jidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jmodeltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdeposittxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jyeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jmiletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(109, 109, 109)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deletebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(addbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(update1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletebtn))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmodeltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jyeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jmiletxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jcosttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jdeposittxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));

        dashlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dashlbl.setForeground(new java.awt.Color(255, 255, 255));
        dashlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashlbl.setText("DASHBOARD");
        dashlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashlblMouseClicked(evt);
            }
        });

        vlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vlbl.setForeground(new java.awt.Color(255, 255, 255));
        vlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vlbl.setText("VEHICLE");
        vlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vlblMouseClicked(evt);
            }
        });

        clbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clbl.setForeground(new java.awt.Color(255, 255, 255));
        clbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clbl.setText("CUSTOMER");
        clbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clblMouseClicked(evt);
            }
        });

        inlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inlbl.setForeground(new java.awt.Color(255, 255, 255));
        inlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inlbl.setText("CHECK-IN");
        inlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inlblMouseClicked(evt);
            }
        });

        outlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        outlbl.setForeground(new java.awt.Color(255, 255, 255));
        outlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outlbl.setText("CHECK-OUT");
        outlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outlblMouseClicked(evt);
            }
        });

        loglbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loglbl.setForeground(new java.awt.Color(255, 255, 255));
        loglbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loglbl.setText("LOGOUT");
        loglbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loglblMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashicon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(loglbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(outlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dashlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dashlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(outlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        tblcar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        tblcar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Vehicle ID", "Model", "Year", "Mileage", "Cost", "Deposit", "Availability"
            }
        ));
        tblcar.setGridColor(new java.awt.Color(255, 255, 255));
        tblcar.setRowHeight(40);
        tblcar.setSelectionBackground(new java.awt.Color(51, 0, 102));
        tblcar.setSelectionForeground(new java.awt.Color(153, 204, 255));
        jScrollPane1.setViewportView(tblcar);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        String vid = jidtxt.getText().trim();
        String model = jmodeltxt.getText().trim();
        String yearStr = jyeartxt.getText().trim();
        String mileageStr = jmiletxt.getText().trim();
        String costStr = jcosttxt.getText().trim();
        String depositStr = jdeposittxt.getText().trim();
        String availability = (String) combo1.getSelectedItem();

        // Validate the input for vid
        if (vid.isEmpty() && model.isEmpty() && yearStr.isEmpty() && mileageStr.isEmpty() && costStr.isEmpty() && depositStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All input fields are empty. Please enter vehicle details.");
            return;
        }

        if (!vid.matches("^M\\d+$")) {
            JOptionPane.showMessageDialog(this, "VID must start with 'M' followed by numbers.");
            return;
        }

        // Validate the input for model
        if (!model.matches("^[a-zA-Z]+$")) {
            JOptionPane.showMessageDialog(this, "Model must contain only alphabet letters.");
            return;
        }

        // Validate the input for year
        int year;
        try {
            year = Integer.parseInt(yearStr);
            if (year < 1998 || year > 2023) {
                JOptionPane.showMessageDialog(this, "Year must be between 1998 and 2023.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid numeric value for Year.");
            return;
        }

        // Validate the input for mileage
        int mileage;
        try {
            mileage = Integer.parseInt(mileageStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid numeric value for Mileage.");
            return;
        }

        // Validate the input for cost
        int cost;
        try {
            cost = Integer.parseInt(costStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid numeric value for Cost.");
            return;
        }

        // Validate the input for deposit
        int deposit;
        try {
            deposit = Integer.parseInt(depositStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid numeric value for Deposit.");
            return;
        }

        try {
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/carrental?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
            String sql = "INSERT INTO vehicle (vid, model, year, mileage, cost, deposit, availability) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement preparedStatement = connection.prepareStatement(sql);

            preparedStatement.setString(1, vid);
            preparedStatement.setString(2, model);
            preparedStatement.setInt(3, year);
            preparedStatement.setInt(4, mileage);
            preparedStatement.setInt(5, cost);
            preparedStatement.setInt(6, deposit);
            preparedStatement.setString(7, availability);

            int rowsAffected = preparedStatement.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Vehicle details added successfully!");
                displayVehicleData();
                clearFormFields();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add vehicle.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
        }           // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_addbtnActionPerformed


    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        int selectedRow = tblcar.getSelectedRow();
        if (selectedRow != -1) {
            // Get the updated data from the text fields and combo box
            String updatedcid = jidtxt.getText();
            String updatedmodel = jmodeltxt.getText();
            String updatedyear = jyeartxt.getText();
            String updatedmile = jmiletxt.getText();
            String updatedcost = jcosttxt.getText();
            String updateddeposit = jdeposittxt.getText();
            String updatedStatus = (String) combo1.getSelectedItem();

            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to update this car?", "Confirm Update", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                // Update the data in the table (user interface)
                DefaultTableModel tableModel = (DefaultTableModel) tblcar.getModel();
                tableModel.setValueAt(updatedcid, selectedRow, 0);
                tableModel.setValueAt(updatedmodel, selectedRow, 1);
                tableModel.setValueAt(updatedyear, selectedRow, 2);
                tableModel.setValueAt(updatedmile, selectedRow, 3);
                tableModel.setValueAt(updatedcost, selectedRow, 4);
                tableModel.setValueAt(updateddeposit, selectedRow, 5);
                tableModel.setValueAt(updatedStatus, selectedRow, 6);

                // Update the data in the MySQL table
                try {
                    // Define the SQL query to update the record in the database
                    try (java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/carrental?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "")) {
                        // Define the SQL query to update the record in the database
                        String sql = "UPDATE vehicle SET model=?, year=?, mileage=?, cost=?, deposit=?, availability=? WHERE vid=?";
                        // Prepare the statement
                        PreparedStatement preparedStatement = connection.prepareStatement(sql);
                        preparedStatement.setString(1, updatedmodel);
                        preparedStatement.setString(2, updatedyear);
                        preparedStatement.setString(3, updatedmile);
                        preparedStatement.setString(4, updatedcost);
                        preparedStatement.setString(5, updateddeposit);
                        preparedStatement.setString(6, updatedStatus);
                        preparedStatement.setString(7, updatedcid);
                        // Execute the update
                        int rowsAffected = preparedStatement.executeUpdate();
                        if (rowsAffected > 0) {
                            JOptionPane.showMessageDialog(this, "Car updated successfully.");
                        } else {
                            JOptionPane.showMessageDialog(this, "Failed to update car in the database.");
                        }
                        // Close the database connection
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a car to update.");
        }// TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_update1ActionPerformed

    private void dashlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashlblMouseClicked
        Dashboard newform = new Dashboard();
        newform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        newform.pack();
        newform.setVisible(true);
        dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_dashlblMouseClicked

    private void vlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vlblMouseClicked
        VehicleRegistration newform = new VehicleRegistration();
        newform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        newform.pack();
        newform.setVisible(true);
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_vlblMouseClicked

    private void clblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clblMouseClicked
        CustomerRegistration newform = new CustomerRegistration();
        newform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        newform.pack();
        newform.setVisible(true);
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_clblMouseClicked

    private void inlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inlblMouseClicked
        Booking newform = new Booking();
        newform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        newform.pack();
        newform.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_inlblMouseClicked

    private void outlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outlblMouseClicked
        CheckOut newform = new CheckOut();
        newform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        newform.pack();
        newform.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_outlblMouseClicked

    private void loglblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loglblMouseClicked
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to Logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            // User clicked "Yes", so proceed with the logout
            dispose();
            LoginForm newform = new LoginForm();
            newform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            newform.pack();
            newform.setVisible(true);
        } else {
            // User clicked "No," so take no action
        }        // TODO add your handling code here:
    }//GEN-LAST:event_loglblMouseClicked

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        int selectedRow = tblcar.getSelectedRow();
        if (selectedRow != -1) {
            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this car?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                DefaultTableModel tableModel = (DefaultTableModel) tblcar.getModel();

                // Get the carRegistration value from the selected row
                String vid = (String) tableModel.getValueAt(selectedRow, 0); // Assuming carRegistration is in the first column

                // Remove the selected row from the table
                tableModel.removeRow(selectedRow);

                try {
                    try ( // Establish a database connection
                            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/carrental?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "")) {
                        String sql = "DELETE FROM vehicle WHERE vid = ?";

                        PreparedStatement preparedStatement = connection.prepareStatement(sql);
                        preparedStatement.setString(1, vid);

                        int rowsAffected = preparedStatement.executeUpdate();

                        if (rowsAffected > 0) {
                            JOptionPane.showMessageDialog(this, "Car deleted successfully.");
                        } else {
                            JOptionPane.showMessageDialog(this, "Failed to delete car from the database.");
                        }
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a car to delete.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_deletebtnActionPerformed

    private void displayVehicleData() {
        try (
                // Establish a database connection
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/carrental?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", ""); PreparedStatement preparedStatement = connection.prepareStatement("SELECT vid, model, year, mileage, cost, deposit, availability FROM vehicle;"); ResultSet resultSet = preparedStatement.executeQuery();) {
            DefaultTableModel tableModel = (DefaultTableModel) tblcar.getModel();

            // Clear existing data in the table
            tableModel.setRowCount(0);

            while (resultSet.next()) {
                String vid = resultSet.getString("vid");
                String model = resultSet.getString("model");
                String year = resultSet.getString("year");
                String mileage = resultSet.getString("mileage");
                String cost = resultSet.getString("cost");
                String deposit = resultSet.getString("deposit");
                String availability = resultSet.getString("availability");

                // Add the fetched data as a new row in the table
                tableModel.addRow(new Object[]{vid, model, year, mileage, cost, deposit, availability});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
        // TODO add your handling code here:
        // TODO add your handling code here:
    }

    private void selectRow(java.awt.event.MouseEvent evt) {
        int selectedRow = tblcar.getSelectedRow();
        if (selectedRow != -1) {
            // A row is selected, so you can retrieve the data from the selected row
            DefaultTableModel tableModel = (DefaultTableModel) tblcar.getModel();
            String cid = (String) tableModel.getValueAt(selectedRow, 0);
            String model = (String) tableModel.getValueAt(selectedRow, 1);
            String year = (String) tableModel.getValueAt(selectedRow, 2);
            String mile = (String) tableModel.getValueAt(selectedRow, 3);
            String cost = (String) tableModel.getValueAt(selectedRow, 4);
            String deposit = (String) tableModel.getValueAt(selectedRow, 5);
            String status = (String) tableModel.getValueAt(selectedRow, 6);

            // Populate the text fields and combo box with the selected car's data
            jidtxt.setText(cid);
            jmodeltxt.setText(model);
            jyeartxt.setText(year);
            jmiletxt.setText(mile);
            jcosttxt.setText(cost);
            jdeposittxt.setText(deposit);
            combo1.setSelectedItem(status);

            // You can also enable the "Update" and "Delete" buttons here if needed
            update1.setEnabled(true);
            deletebtn.setEnabled(true);
        }         // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JLabel clbl;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JLabel dashlbl;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel inlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jcosttxt;
    private javax.swing.JTextField jdeposittxt;
    private javax.swing.JTextField jidtxt;
    private javax.swing.JTextField jmiletxt;
    private javax.swing.JTextField jmodeltxt;
    private javax.swing.JTextField jyeartxt;
    private javax.swing.JLabel loglbl;
    private javax.swing.JLabel outlbl;
    private javax.swing.JTable tblcar;
    private javax.swing.JButton update1;
    private javax.swing.JLabel vlbl;
    // End of variables declaration//GEN-END:variables
}
